### PR TITLE
Update deps / code format

### PR DESCRIPTION
**Pull request by pups3s**
* httpoison ~0.11 => ~1.0
* poison ~3.0 => ~3.1
* credo ~0.5 => ~0.9.1
* some credo fixes in tests
* some magic formatting with elixir 1.6 built-in formatter

### CODE REVIEW

**Comment by ayrat555** [comment]
@pups3s thank you! looks good to me. can you bump library version and create CHANGELOG.md file with your changes?

**Comment by ayrat555** [comment]
also elixir version should be changed from 1.3 to 1.6 in mix.exs

**Comment by pups3s** [comment]
@ayrat555 thanks :)

Changes are done, but seems you need to up elixir version in Semaphore.

**Comment by greysteil** [comment]
Would you be up for automatically creating dependency-update PRs? I built [Dependabot](https://dependabot.com) for that - it will put in a PR every time there's a dependency in your `mix.lock` that can be updated. (Totally free, obviously - I'm trying to get some more people using it.)

**Comment by ayrat555** [comment]
@pups3s I can give you admin access to the repo and hex.pm. you can try Dependabot if you want

**Comment by pups3s** [comment]
So, i tried it

@greysteil 
interesting tool, I like it 😄  Works well

@ayrat555 
Unfortunately I can't connect Dependabot to this repo by being collaborator.
Seems like only owner can do this :)

**Comment by ayrat555** [comment]
@pups3s so now you're admin. btw I need your email to grant you access to hex.pm

**Comment by pups3s** [comment]
@ayrat555 I see, you are really serious guy 😄 

Wrote to you via mail

**Pull request merged**
